global using Aqarak_WebAPI.DTOs;
global using Aqarak_WebAPI.Models;
global using Aqarak_WebAPI.Repository;
global using Microsoft.EntityFrameworkCore;
global using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
global using static System.Net.Mime.MediaTypeNames;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.AspNetCore.SignalR;
global using Aqarak_WebAPI.Interfaces;
